/**
 *  Copyright (c) 2020, 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
import { h, Component, Prop, Event, EventEmitter, Element, Method, Watch, State } from '@stencil/core';
import { WidgetBase } from '../gc-widget-base/gc-widget-base';
import { WidgetBaseProps } from '../gc-widget-base/gc-widget-base-props';
import { WidgetTabPanelProps } from './gc-widget-tab-panel-props';

/**
 * `gc-widget-link-tab-panel` is a widget to host an external html file.
 *
 * @label Tab Panel With Link
 * @group Containers
 * @demo
 * @usage
 */
@Component({
    tag: 'gc-widget-link-tab-panel',
    styleUrl: 'gc-widget-link-tab-panel.scss',
    shadow: true
})
export class WidgetLinkTabPanel implements WidgetBaseProps, WidgetTabPanelProps {
    private activated = false;
    private iframe: HTMLIFrameElement;

    private base = new (
        class extends WidgetBase {
            get element() {
                return (this.parent as WidgetLinkTabPanel).el;
            }
        })(this);

    /**
     * The hyperlink to the external html.
     * @order 2
     */
    @Prop() href: string;

    @State() src: string;

    render() {
        // JSXON
        return (
            <iframe ref={ (el: HTMLIFrameElement) => this.iframe = el } src={ this.src }></iframe>
        );
        // JSXOFF
    }

    componentDidRender() {
        this.iframe.addEventListener('load', () => {
            this.iframe.contentWindow.addEventListener('resize', () => this.updateIFrameStyles());
            this.updateIFrameStyles();
        });

    }

    private getElmHeight(window: Window, element: HTMLElement) {
        const style = window.getComputedStyle(element);
        return [
            'margin-top', 'margin-bottom',
            'border-top', 'border-bottom',
            'padding-top', 'padding-bottom',
            'height'
        ].map(k => parseFloat(style.getPropertyValue(k))).reduce((prev, cur) => prev + cur);
    }

    private updateIFrameStyles() {
        const body = this.iframe.contentDocument.body;
        body.style.overflow = 'hidden';
        body.style.display = 'inline-block';

        this.iframe.style.height = this.getElmHeight(this.iframe.contentWindow, body) + 'px';
    }

    /**
     * Activate the tab and start loading the content.
     */
    @Method()
    async activate() {
        this.activated = true;
        this.src = this.href;
    }

    @Watch('href')
    onHrefChanged() {
        if (this.activated) {
            this.src = this.href;
        }
    }

    @Watch('label')
    @Watch('iconName')
    @Watch('iconPath')
    @Watch('hidden')
    @Watch('tooltip')
    onInfoChanged() {
        this.infoChangedEvent.emit();
    }

    // #region gc-widget-base/gc-widget-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The widget element.
     */
    @Element() el: HTMLElement;

    /**
     * Sets to `true` to hide the element, otherwise `false`.
     *
     * @order 200
     */
    @Prop({ reflect: true }) hidden: boolean = false;

    /**
     * Fired when a CSS property has changed.
     **/
    @Event({ eventName: 'css-property-changed' }) cssPropertyChanged: EventEmitter<{ name: string; value: string }>;

    /**
     * Sets the CSS property.
     *
     * @param {string} name the element style name
     * @param {string} value the new CSS property to be set
     */
    @Method()
    async setCSSProperty(name: string, value: string): Promise<void> {
        value = value.replace(/^[ ]+|[ ]+$/g, '');
        if (await this.getCSSProperty(name) !== value) {
            this.el.style.setProperty(name, value);
            this.cssPropertyChanged.emit({ name: name, value: value });
        }
    }

    /**
     * Returns the value of a CSS property.
     *
     * @param {string} name the element style property
     * @returns {string} the value of the property
     */
    @Method()
    async getCSSProperty(name: string): Promise<string> {
        return getComputedStyle(this.el).getPropertyValue(name).trim();
    }

    /**
     * Refresh the widget.
     */
    @Method()
    async refresh(): Promise<void> {
        return this.el['forceUpdate']();
    }
    // #endregion
    // #region gc-widget-tab/gc-widget-tab-panel-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The tab label.
     * @order 2
     */
    @Prop() label: string = 'Tab';

    /**
     * The name of the icon.
     * @order 3
     */
    @Prop() iconName: string;

    /**
     * The icon file path.
     * @order 4
     */
    @Prop() iconPath: string;

    /**
     * @hidden
     */
    @Event({ eventName: 'on-tab-panel-info-changed' }) infoChangedEvent: EventEmitter;
    // #endregion
    // #region gc-widget-base/gc-widget-base-tooltip-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * Controls the tooltip that is displayed for this widget.
     * @order 210
     */
    @Prop() tooltip: string;
    // #endregion

}
