/**
 *  Copyright (c) 2020, 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS'
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
import { Prop, Component, Element } from '@stencil/core';
import { GcTargetDeviceNameProps } from './gc-target-device-name-props';
import { GcTargetDeviceProgramLoaderProps } from './gc-target-device-program-loader-props';
import { ServicesRegistry } from '../gc-core-services/lib/ServicesRegistry';
import { targetConfigServiceType } from '../gc-service-target-config/lib/TargetConfigService';
import { createPropertyAutoFill, IPropertyAutoFill } from '../gc-core-assets/lib/GcDesigner';

const targetConfigService = ServicesRegistry.getService(targetConfigServiceType);

/**
 * `gc-target-device-programmable` is a non visual component specifying properties for a device that is programmable.
 * This component does not perform any operations on the target and is only used to provide default properties to other
 * components in a target configuration where it is referenced by id using the deviceId property.
 *
 * @usage
 * @label Programmable Device
 * @group Transports, Models, and Codecs
 */
@Component({
    tag: 'gc-target-device-programmable',
    shadow: true
})

export class GCTargetDeviceProgrammable implements GcTargetDeviceNameProps, GcTargetDeviceProgramLoaderProps {
    private propertyAutoFill: IPropertyAutoFill = undefined;

    connectedCallback() {
        this.propertyAutoFill = createPropertyAutoFill(this.el);
        this.propertyAutoFill.register('deviceName', async () => (await targetConfigService.getDevices()).map(device => device.id));
    };

    disconnectedCallback() {
        this.propertyAutoFill.unregister('deviceName');
    }

    @Element() el: HTMLElement;

    // #region gc-target-device-programmable/gc-target-device-name-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The name of the target device.  This should be the part number or name of the device for the
     * purposes of loading program or symbols, or creating a default .ccxml file.
     *
     * @order 44
     */
    @Prop() deviceName: string;
    // #endregion
    // #region gc-target-device-programmable/gc-target-device-program-loader-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The name of the core to use.  This is optional and if omitted, the first
     * programmable core in the target configuration will be used.
     *
     * @order 47
     */
    @Prop() coreName: string;

    /**
     * The file path to the target program or binary image to use for the purposes of reading
     * symbols, and loading or flashing the program to the target.
     *
     * @order 48
     */
    @Prop() programOrBinPath: string;

    /**
     * The file path to the target program for the purposes of verifying if the device has the same
     * program before loading a binary file.  This is optional and is only useful when programOrBinPath
     * points to a binary image.
     *
     * @order 49
     */
    @Prop() verifyProgramPath: string;

    /**
     * The address to load a binary image into.  This is optional and is only useful when programOrBinPath
     * points to a binary image.  The address can be provided in hexadecimal notation if preceded by '0x'.
     *
     * @order 50
     */
    @Prop() loadAddress: number;

    /**
     * Timeout in millisecond for flashing/loading image onto the device.  This is optional and if omitted
     * the default is 75 seconds.  If more time is required, then this property should be set to an appropriate
     * higher value.
     *
     * @order 51
     */
    @Prop() timeout: number;

    /**
     * A flag indicating that the target program is stored in volatile static ram instead of flash memory.
     * Use this flag to indicate that the program image will not necessarily be preserved when reconnecting to
     * the same target, so the program must be loaded each time.
     *
     * @order 63
     */
    @Prop() sram: boolean = false;
    // #endregion

}
