/**
 *  Copyright (c) 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS'
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
import { Prop, Component } from '@stencil/core';
import { GcTargetDeviceRegisterProps } from './gc-target-device-register-props';
import { GcTargetDeviceAddressProps } from './gc-target-device-address-props';

/**
 * `gc-target-device-analog` is a non visual component specifying properties for an analog device, like a sensor, which has
 * registers that are available through an external bus (I2C, SPI, UART, etc...). This component does not perform any
 * operations on the target and is only used to provide default properties to other components in a target configuration
 * where it is referenced by id using the deviceId property, like the gc-model-register.
 *
 * @usage
 * @label Analog Device
 * @group Transports, Models, and Codecs
 */
@Component({
    tag: 'gc-target-device-analog',
    shadow: true
})

export class GcTargetDeviceAnalog implements GcTargetDeviceRegisterProps, GcTargetDeviceAddressProps {

    // #region gc-target-device-analog/gc-target-device-register-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The relative or absolute path to a json file containing the register definitions for an analog device.name of the target device.
     *
     * @order 34
     */
    @Prop() registerInfo: string;

    /**
     * The name of the register to use for device verification.  If none specified, then no verification will occur.
     *
     * @order 58
     */
    @Prop() verifyRegisterName: string;

    /**
     * The value expected to be read from the verify register after applying the verification mask.  If not specified,
     * any value read for this register will be excepted as valid.
     *
     * @order 59
     */
    @Prop() verifyValue: string;

    /**
     * An optional mask value to be applied to the register value before comparing it to the verify value.  If not specified,
     * no mask will be applied, and the register value must match exactly the verify value.
     *
     * @order 60
     */
    @Prop() verifyMask: string;

    /**
     * An optional comma separated list of I2C device addresses to scan for verification of the device.
     * For example, verifyDeviceAddress="0x40,0x48,0x50".
     *
     * @order 62
     */
    @Prop() verifyDeviceAddress: string;

    /**
     * The optional flag that if true indicates that multi-device support is required.  All devices must be
     * of the same class, and therefore same register set.  Also, they all must be available on the same
     * interface through a single codec which also has multi-device support.
     *
     * @order 94
     */
    @Prop() isDeviceArray: boolean = false;
    // #endregion
    // #region gc-target-device-analog/gc-target-device-address-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The I2C bus address of this device.
     *
     * @order 39
     */
    @Prop() deviceAddress: string;
    // #endregion

}
