/**
 *  Copyright (c) 2020, 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS'
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
import { Prop, Component, Element } from '@stencil/core';
import { GcCodecBaseProps } from '../gc-target-configuration/gc-codec-base-props';
import { XdsTransport } from './lib/XdsTransport';
import { GcTargetDeviceConnectionProps } from '../gc-target-device-programmable/gc-target-device-connection-props';
import { GcTargetDeviceNameProps } from './../gc-target-device-programmable/gc-target-device-name-props';
import { createTargetParamsProxy } from '../gc-target-device-programmable/TargetDeviceParamsProxy';
import { ServicesRegistry } from '../gc-core-services/lib/ServicesRegistry';
import { targetConfigServiceType } from '../gc-service-target-config/lib/TargetConfigService';
import { createPropertyAutoFill, IPropertyAutoFill } from '../gc-core-assets/lib/GcDesigner';

const targetConfigService = ServicesRegistry.getService(targetConfigServiceType);

/**
 * `gc-transport-xds` is a non visual component for communicating with the target over JTag scan
 * chain using read and write memory with symbolic information.  All global symbols are available
 * for binding, including structures and arrays.
 *
 * @usage
 * @label XDS Transport
 * @group Transports, Models, and Codecs
 * @archetype <gc-transport-xds id="xds"></gc-transport-xds>
 */
@Component({
    tag: 'gc-transport-xds',
    shadow: true
})

export class GcTransportXds implements GcCodecBaseProps, GcTargetDeviceConnectionProps {
    private impl: XdsTransport | undefined = undefined;
    private propertyAutoFill: IPropertyAutoFill = undefined;

    connectedCallback() {
        const params = createTargetParamsProxy(this.el);
        this.impl = new XdsTransport(params);

        this.propertyAutoFill = createPropertyAutoFill(this.el);
        this.propertyAutoFill
            .register('deviceName', async () => (await targetConfigService.getDevices()).map(device => device.id))
            .register('connectionName', async () => (await targetConfigService.getConnections(params['deviceName'])).map(connection => connection.id));
    }

    disconnectedCallback() {
        this.propertyAutoFill.unregister('deviceName').unregister('connectionName');
        this.impl.dispose();
    }

    // #region gc-target-configuration/gc-codec-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * A flag indicating that this model, transport, codec, or device is not necessary for connecting
     * to the target.  Any failure should not prevent the connection from continuing, which may
     * result in a partial connection.
     *
     * @order 77
     */
    @Prop() optional: boolean = false;

    /**
     * An optional identifier of a target device that is associated with this model, transport or codec.
     * Specifying a target device indicates that this component is necessary and/or optional for
     * properly connecting to the target device.  If a required component fails to connect, other components
     * will not be connected that are associated with the same device by id.  This way you can associate
     * a gc-target-program-loader with a gc-transport-usb so that if the program fails to load the transport
     * will not attempt to connect and will fail, unless the gc-target-program-loader has the optional property
     * set.  The absence of a target device indicates this is necessary and/or optional
     * for connecting to any device.  As a result, specifying the deviceId is not necessary if you only have
     * one device in you target configuration, any failure to connect will result in the entire connection
     * being aborted.
     *
     * @order 80
     */
    @Prop() deviceId: string;

    @Element() el: HTMLElement;
    // #endregion
    // #region gc-target-device-programmable/gc-target-device-connection-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The name of the connection to use to connect to the target for the purposes of loading a program or symbols.
     *
     * @order 45
     */
    @Prop() connectionName: string;

    /**
     * The path to a .ccxml file that describes the target configuration to be used to load programs or
     * symbols with.  If this property is omitted, a default .ccxml file will be generated using the deviceName,
     * and connectionName properties provided.
     *
     * @order 46
     */
    @Prop() ccxmlPath: string;
    // #endregion
    // #region gc-target-device-programmable/gc-target-device-name-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The name of the target device.  This should be the part number or name of the device for the
     * purposes of loading program or symbols, or creating a default .ccxml file.
     *
     * @order 44
     */
    @Prop() deviceName: string;
    // #endregion

}
