/**
 *  Copyright (c) 2020, 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
import { h, Component, Prop, Event, EventEmitter, Element, Method, Listen } from '@stencil/core';
import { WidgetBase } from '../gc-widget-base/gc-widget-base';
import { WidgetBaseProps } from '../gc-widget-base/gc-widget-base-props';
import { WidgetBaseDisabledProps } from '../gc-widget-base/gc-widget-base-disabled-props';
import { ActionRegistry } from '../gc-widget-menu/lib/ActionRegistry';
import { WidgetBaseTooltipProps } from '../gc-widget-base/gc-widget-base-tooltip-props';

/**
 * `gc-widget-toolbar-action` a toolbar item that performs an action. These are typically dropped onto an
 * existing gc-widget-toolbar element. Actions are register in javascript so that they can be reused
 * in more than one place; for example, in menu bar adn context menus, and also keep track of state like
 * enabled and disabled in one place. Toolbar action widgets will automatically show themselves as disabled
 * when the registered action is not found, or it has been explicity disabled.
 *
 * @label Toolbar Action
 * @group Menus & Toolbars
 * @demo
 * @usage
 */
@Component({
    tag: 'gc-widget-toolbar-action',
    styleUrl: 'gc-widget-toolbar-action.scss',
    shadow: true
})
export class WidgetToolbarAction implements WidgetBaseProps, WidgetBaseTooltipProps, WidgetBaseDisabledProps {
    private base = new (
        class extends WidgetBase {
            get element() {
                return (this.parent as WidgetToolbarAction).el;
            }
        })(this);

    /**
     * Identifies the action to perform when this menubar action is clicked.
     *
     * @order 3
     */
    @Prop()
    actionId: string;

    /**
     * The icon to be displayed (svgFilename:iconName, eg. action:info)
     */
    @Prop()
    icon: string = 'action:info';

    render() {
        // JSXON
        return this.base.render(
            <div id="element-container">
                <gc-widget-icon icon={ this.icon } appearance="custom"></gc-widget-icon>
                { /* TODO: add support for drop down menu and toggle state */ }
            </div>,
            { tooltip: this.tooltip }
        );
        // JSXOFF
    }

    componentWillLoad() {
        window.addEventListener('gc-command-update', this.updateStates.bind(this));
        this.updateStates();
    }

    @Listen('mouseup')
    noMouseUpHdlr() {
        if (!this.disabled) {
            window.dispatchEvent(new CustomEvent('gc-command-run', { detail: { id: this.actionId } }));
        }
    }

    /**
     * Force the action to update the internal states.
     */
    @Method()
    async updateStates() {
        if (ActionRegistry.isEnabled(this.actionId)) {
            this.el.removeAttribute('disabled');
        } else {
            this.el.setAttribute('disabled', '');
        }

        if (ActionRegistry.isVisible(this.actionId)) {
            this.el.removeAttribute('hidden');
        } else {
            this.el.setAttribute('hidden', '');
        }

        if (ActionRegistry.isChecked(this.actionId)) {
            this.el.classList.add('checked');
        } else {
            this.el.classList.remove('checked');
        }
    }

    // #region gc-widget-base/gc-widget-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The widget element.
     */
    @Element() el: HTMLElement;

    /**
     * Sets to `true` to hide the element, otherwise `false`.
     *
     * @order 200
     */
    @Prop({ reflect: true }) hidden: boolean = false;

    /**
     * Fired when a CSS property has changed.
     **/
    @Event({ eventName: 'css-property-changed' }) cssPropertyChanged: EventEmitter<{ name: string; value: string }>;

    /**
     * Sets the CSS property.
     *
     * @param {string} name the element style name
     * @param {string} value the new CSS property to be set
     */
    @Method()
    async setCSSProperty(name: string, value: string): Promise<void> {
        value = value.replace(/^[ ]+|[ ]+$/g, '');
        if (await this.getCSSProperty(name) !== value) {
            this.el.style.setProperty(name, value);
            this.cssPropertyChanged.emit({ name: name, value: value });
        }
    }

    /**
     * Returns the value of a CSS property.
     *
     * @param {string} name the element style property
     * @returns {string} the value of the property
     */
    @Method()
    async getCSSProperty(name: string): Promise<string> {
        return getComputedStyle(this.el).getPropertyValue(name).trim();
    }

    /**
     * Refresh the widget.
     */
    @Method()
    async refresh(): Promise<void> {
        return this.el['forceUpdate']();
    }
    // #endregion
    // #region gc-widget-base/gc-widget-base-tooltip-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * Controls the tooltip that is displayed for this widget.
     * @order 210
     */
    @Prop() tooltip: string;
    // #endregion
    // #region gc-widget-base/gc-widget-base-disabled-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * Controls the widget disabled state.
     * @order 202
     */
    @Prop({ reflect: true }) disabled: boolean = false;
    // #endregion

}
