/**
 *  Copyright (c) 2020, 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
import { Component, Prop, Element } from '@stencil/core';
import { GcCodecBaseProps } from '../gc-target-configuration/gc-codec-base-props';
import { IDelimitedTextCodecParams, DelimitedTextCodec } from '../gc-codec-delimited-text/lib/DelimitedTextCodec';

/**
 * `gc-codec-delimited-text` is a non visual component for encoding/decoding text packets that use a specific
 * character string as a delimiter, for example a carriage return.  Optionally, if the packet contains delimiter
 * characters, you can also provide an escape character.
 *
 * @usage
 * @label Delimited Text Codec
 * @group Transports, Models, and Codecs
 * @archetype <gc-codec-delimited-text id="cr"></gc-codec-delimited-text>
 */
@Component({
    tag: 'gc-codec-delimited-text',
    shadow: true
})

export class GcCodecDelimitedText implements GcCodecBaseProps, IDelimitedTextCodecParams {

    private impl: DelimitedTextCodec | undefined = undefined;

    /**
     * This character sequence is used to delimit packets of data.  Whenever this codec encounters
     * this sequence of characters, all the data accumlated up until this point is passed along to
     * the next codec in the chain as an entire packet.  This property is optional and if not
     * present the default delimiter used is the carrage return.
     *
     * @order 30
     */
    @Prop() delimiter: string = undefined;

    /**
     * This character sequence is used to escape the delimiter sequence when it occurs inside the packet data.
     * During encoding, any delimiter sequence will have one escapeChar inserted before it to indicated that
     * it is part of the packet and is not a real delimiter.  So two escape sequenes in a row represent a
     * single escape sequence in the data, and will be decoded as such.
     * This property is optional, and if omitted, there is no
     * escape sequencing used at all, and it is assumed that delimiters will not occur in the packet data.
     *
     * @order 33
     */
    @Prop() escapeChar: string = undefined;

    // #region gc-target-configuration/gc-codec-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * A flag indicating that this model, transport, codec, or device is not necessary for connecting
     * to the target.  Any failure should not prevent the connection from continuing, which may
     * result in a partial connection.
     *
     * @order 77
     */
    @Prop() optional: boolean = false;

    /**
     * An optional identifier of a target device that is associated with this model, transport or codec.
     * Specifying a target device indicates that this component is necessary and/or optional for
     * properly connecting to the target device.  If a required component fails to connect, other components
     * will not be connected that are associated with the same device by id.  This way you can associate
     * a gc-target-program-loader with a gc-transport-usb so that if the program fails to load the transport
     * will not attempt to connect and will fail, unless the gc-target-program-loader has the optional property
     * set.  The absence of a target device indicates this is necessary and/or optional
     * for connecting to any device.  As a result, specifying the deviceId is not necessary if you only have
     * one device in you target configuration, any failure to connect will result in the entire connection
     * being aborted.
     *
     * @order 80
     */
    @Prop() deviceId: string;

    @Element() el: HTMLElement;
    // #endregion

    connectedCallback() {
        this.impl = new DelimitedTextCodec(this.el);
    }

    disconnectedCallback() {
        this.impl.dispose();
    }
}