/**
 *  Copyright (c) 2021, Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import { Prop, Component, Element } from '@stencil/core';
import { Usb2anySpiCodec, IUsb2anySpiCodecParams } from '../gc-codec-usb2any-spi/lib/Usb2anySpiCodec';
import { GcCodecBaseProps } from '../gc-target-configuration/gc-codec-base-props';
import { GcCodecSpiBaseProps } from '../gc-target-configuration/gc-codec-spi-base-props';
import { createTargetParamsProxy } from '../gc-target-device-programmable/TargetDeviceParamsProxy';

/**
 * `gc-codec-usb2any-spi` is a non visual component for encoding and decoding SPI messages for USB2ANY.
 *
 * @usage
 * @label USB2ANY SPI Codec
 * @group Transports, Models, and Codecs
 */
@Component({
    tag: 'gc-codec-usb2any-spi',
    shadow: true
})

export class GcCodecUsb2anySpi implements GcCodecSpiBaseProps, GcCodecBaseProps, IUsb2anySpiCodecParams {
    private impl: Usb2anySpiCodec | undefined;

    connectedCallback() {
        this.impl = new Usb2anySpiCodec(createTargetParamsProxy(this.el));
    }

    disconnectedCallback() {
        this.impl.dispose();
    }

    /**
     * The edge of the clock on which data is captured.
     *
     * @order 50
     */
    @Prop() clockPhase: 'following' | 'first' = 'first';

    /**
     * Defines which clock state is considered inactive.
     *
     * @order 51
     */
    @Prop() clockPolarity: 'low' | 'high' = 'low';

    /**
     * Defines which bit of each byte is sent first.
     *
     * @order 52
     */
    @Prop() bitDirection: 'lsb' | 'msb' = 'msb';

    /**
     * Number of data bits in each byte transferred.
     *
     * @order 53
     */
    @Prop() characterLength: 7 | 8 = 8;

    /**
     * Defines how the chip select signal is generated.
     *
     * @order 54
     */
    @Prop() latchType: 'byte' | 'packet' | 'word' | 'no_cs' | 'pulse_after_packet' = 'packet';

    /**
     * Defines the state in which the chip select signal is active.
     *
     * @order 55
     */
    @Prop() latchPolarity: 'high' | 'low' = 'low';

    /**
     * Clock divider that sets the SPI bit rate. It is equal to 24000000/bit_rate_in_bits_per_second.
     *
     * @order 56
     */
    @Prop() clockDivider = 1;

    /**
     * Offset of read command bit. Exclusive with writeBitOffset.
     *
     * @order 57
     */
    @Prop() readBitOffset: number;

    /**
     * Offset of write command bit. Exclusive with readBitOffset.
     *
     * @order 58
     */
    @Prop() writeBitOffset: number;

    // #region gc-target-configuration/gc-codec-spi-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * Number of address bits.
     *
     * @order 61
     */
    @Prop() addressBits = 6;

    /**
     * Offset of address bits.
     *
     * @order 62
     */
    @Prop() addressBitsOffset = 8;

    /**
     * Number of data bits.
     *
     * @order 63
     */
    @Prop() dataBits = 8;

    /**
     * Offset of data bits.
     *
     * @order 64
     */
    @Prop() dataBitsOffset = 0;

    /**
     * Optional parity.
     *
     * @order 65
     */
    @Prop() parity: 'odd' | 'even';

    /**
     * Offset of parity bits. Used when parity is defined.
     *
     * @order 66
     */
    @Prop() parityBitsOffset = 0;

    // #endregion
    // #region gc-target-configuration/gc-codec-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * A flag indicating that this model, transport, codec, or device is not necessary for connecting
     * to the target.  Any failure should not prevent the connection from continuing, which may
     * result in a partial connection.
     *
     * @order 77
     */
    @Prop() optional: boolean = false;

    /**
     * An optional identifier of a target device that is associated with this model, transport or codec.
     * Specifying a target device indicates that this component is necessary and/or optional for
     * properly connecting to the target device.  If a required component fails to connect, other components
     * will not be connected that are associated with the same device by id.  This way you can associate
     * a gc-target-program-loader with a gc-transport-usb so that if the program fails to load the transport
     * will not attempt to connect and will fail, unless the gc-target-program-loader has the optional property
     * set.  The absence of a target device indicates this is necessary and/or optional
     * for connecting to any device.  As a result, specifying the deviceId is not necessary if you only have
     * one device in you target configuration, any failure to connect will result in the entire connection
     * being aborted.
     *
     * @order 80
     */
    @Prop() deviceId: string;

    @Element() el: HTMLElement;
    // #endregion

}
