/**
 *  Copyright (c) 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import { Component, h, Prop, Element, Method, Event, EventEmitter } from '@stencil/core';
import { WidgetBase } from '../gc-widget-base/gc-widget-base';
import { WidgetBaseProps } from '../gc-widget-base/gc-widget-base-props';
import { GcUtils } from '../gc-core-assets/lib/GcUtils';

/**
 * `gc-widget-container` is a container widget to host child widgets. It supports fixed layout and flex layout
 * for positioning the child widgets. In general, one should be using flex layout to have the application be
 * responsive on different display resolutions. To use flex layout, set the layout style to `horizontal` or
 * `vertical`. Alignment can be set using the `justify` and `align` styles.
 *
 * @label Container
 * @group Containers
 * @css --gc-background-color | The background color | { "kind": "color" }
 * @css --gc-overflow | Controls what happens to content that is too big to fit into an area | { "kind": "select", "options": ["", "visible", "hidden", "scroll", "auto"] }
 * @css --gc-padding | Padding is used to create space around an element's content area
 * @archetype <gc-widget-container style="width: 200px; height: 100px;"></gc-widget-container>
 * @container
 * @border
 * @layout
 * @demo
 * @usage
 */
@Component({
    tag: 'gc-widget-container',
    styleUrl: 'gc-widget-container.scss',
    shadow: true
})
export class WidgetContainer implements WidgetBaseProps {
    private contentElement: HTMLElement;
    private scrollHandler = () => this.el.dispatchEvent(new CustomEvent('scroll'));

    private base = new (
        class extends WidgetBase {
            get element() {
                return this.parent.el;
            }
        })(this);

    /**
     * The heading to display at the top of the container.
     * @order 2
     */
    @Prop({ reflect: true }) heading: string;

    /**
     * Controls the drop shadow depth behind the container.
     * @order 3
     */
    @Prop({ reflect: true }) elevation: '0'|'1'|'2'|'3'|'4'|'5' = '0';

    render() {
        return this.base.render(
            // JSXON
            <div id='root-container'>
                { this.heading ? <div id='heading'>{ this.heading }</div> : undefined }
                <div id='content' class='offsetParentForDesigner'
                    ref={ (e: HTMLElement) => this.contentElement = e }
                    onScroll={ this.scrollHandler }
                >
                    <slot></slot>
                </div>
            </div>
            // JSXOFF
        );
    }

    componentWillLoad() {
        if (GcUtils.isInDesigner) {
            const updateLayoutAttribute = () => {
                if (this.contentElement) {
                    if (this.el.attributes['layout']) {
                        this.contentElement.setAttribute('layout', '');
                    } else {
                        this.contentElement.removeAttribute('layout');
                    }
                }
            };
            const observer = new MutationObserver(updateLayoutAttribute);
            observer.observe(this.el, { attributes: true });
        }
    }

    // #region gc-widget-base/gc-widget-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The widget element.
     */
    @Element() el: HTMLElement;

    /**
     * Sets to `true` to hide the element, otherwise `false`.
     *
     * @order 200
     */
    @Prop({ reflect: true }) hidden: boolean = false;

    /**
     * Fired when a CSS property has changed.
     **/
    @Event({ eventName: 'css-property-changed' }) cssPropertyChanged: EventEmitter<{ name: string; value: string }>;

    /**
     * Sets the CSS property.
     *
     * @param {string} name the element style name
     * @param {string} value the new CSS property to be set
     */
    @Method()
    async setCSSProperty(name: string, value: string): Promise<void> {
        value = value.replace(/^[ ]+|[ ]+$/g, '');
        if (await this.getCSSProperty(name) !== value) {
            this.el.style.setProperty(name, value);
            this.cssPropertyChanged.emit({ name: name, value: value });
        }
    }

    /**
     * Returns the value of a CSS property.
     *
     * @param {string} name the element style property
     * @returns {string} the value of the property
     */
    @Method()
    async getCSSProperty(name: string): Promise<string> {
        return getComputedStyle(this.el).getPropertyValue(name).trim();
    }

    /**
     * Refresh the widget.
     */
    @Method()
    async refresh(): Promise<void> {
        return this.el['forceUpdate']();
    }
    // #endregion

}
