/**
 *  Copyright (c) 2020, 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
import { Component, h, Prop, Method, Event, EventEmitter, Element, Watch, State } from '@stencil/core';
import { WidgetBase } from '../gc-widget-base/gc-widget-base';
import { WidgetBaseTitleProps } from '../gc-widget-base/gc-widget-base-title-props';
import { WidgetBaseProps } from '../gc-widget-base/gc-widget-base-props';
import { GcConsole } from '../gc-core-assets/lib/GcConsole';
import { WidgetBaseTooltipProps } from '../gc-widget-base/gc-widget-base-tooltip-props';
import { WidgetBaseReadonlyProps } from '../gc-widget-base/gc-widget-base-readonly-props';
import './internal/marked.min.js'


declare global {
    interface Window {
        marked: (md: string) => string;
    }
}

const console = new GcConsole('gc-widget-markdown');

/**
 * `gc-widget-markdown` renders a markdown `.md` file.
 *
 * @label Markdown
 * @group Common
 * @demo
 * @usage
 */
@Component({
    tag: 'gc-widget-markdown',
    styleUrl: 'gc-widget-markdown.scss',
    shadow: true
})

export class WidgetMarkdown implements WidgetBaseProps, WidgetBaseTooltipProps, WidgetBaseTitleProps, WidgetBaseReadonlyProps {
    private base = new ( // keep on separate line to enable source mapping
        class extends WidgetBase {
            get element() {
                return (this.parent as WidgetMarkdown).el;
            }
        })(this);

    /**
     * A markdown formatted string.  When changed, triggers re-render.
    */
    @State() text: string;

    /**
     * A path to a markdown file (relative to where the widget is used)
     */
    @Prop() file: string;
    @Watch('file')
    async onFileChanged() {
        try {
            if (!this.file || this.file.trim().length === 0) {
                this.text = 'Please define a valid filepath.';
            }
            // for ti widget documentation use @ti/widget-name/usage.md
            const response = await fetch(this.file);
            if (response.ok) {
                this.text = await response.text();
            } else {
                throw Error(`${response.status}: ${response.statusText}`);
            };

        } catch (e) {
            // if failed to get response
            console.error(e.message);
        }
    }

    /**
     * Set markdown text to display
     * @param markdownText markdown formatted string
     */
    @Method()
    async setText(markdownText: string) {
        this.text = markdownText;
    }

    componentWillLoad() {
        this.onFileChanged();
    }


    render() {
        // JSXON
        return this.base.render(
            <div id="markdown" innerHTML={window.marked(this.text ? this.text : '' )}></div>,
            { caption: this.caption, infoText: this.infoText, tooltip: this.tooltip }
        );
        // JSXOFF
    }

    // #region gc-widget-base/gc-widget-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The widget element.
     */
    @Element() el: HTMLElement;

    /**
     * Sets to `true` to hide the element, otherwise `false`.
     *
     * @order 200
     */
    @Prop({ reflect: true }) hidden: boolean = false;

    /**
     * Fired when a CSS property has changed.
     **/
    @Event({ eventName: 'css-property-changed' }) cssPropertyChanged: EventEmitter<{ name: string; value: string }>;

    /**
     * Sets the CSS property.
     *
     * @param {string} name the element style name
     * @param {string} value the new CSS property to be set
     */
    @Method()
    async setCSSProperty(name: string, value: string): Promise<void> {
        value = value.replace(/^[ ]+|[ ]+$/g, '');
        if (await this.getCSSProperty(name) !== value) {
            this.el.style.setProperty(name, value);
            this.cssPropertyChanged.emit({ name: name, value: value });
        }
    }

    /**
     * Returns the value of a CSS property.
     *
     * @param {string} name the element style property
     * @returns {string} the value of the property
     */
    @Method()
    async getCSSProperty(name: string): Promise<string> {
        return getComputedStyle(this.el).getPropertyValue(name).trim();
    }

    /**
     * Refresh the widget.
     */
    @Method()
    async refresh(): Promise<void> {
        return this.el['forceUpdate']();
    }
    // #endregion
    // #region gc-widget-base/gc-widget-base-tooltip-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * Controls the tooltip that is displayed for this widget.
     * @order 210
     */
    @Prop() tooltip: string;
    // #endregion
    // #region gc-widget-base/gc-widget-base-title-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The widget caption text.
     * @order 207
     */
    @Prop({ reflect: true }) caption: string;

    /**
     * The widget info icon help text.
     * @order 208
     */
    @Prop({ reflect: true }) infoText: string;
    // #endregion
    // #region gc-widget-base/gc-widget-base-readonly-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * Controls the widget readonly state.
     * @order 201
     */
    @Prop({ reflect: true }) readonly: boolean = false;
    // #endregion

}
