/**
 *  Copyright (c) 2020, 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
import { Component, Prop, Element } from '@stencil/core';
import { GcCodecBaseProps } from '../gc-target-configuration/gc-codec-base-props';
import { StreamingDataModel } from '../gc-model-streaming/lib/StreamingDataModel';

/**
 * `gc-model-streaming` is a non visual component for a generic data binding model where
 * data is streammed up from the target.  All the data recieved is in the form of a javascript
 * object.  The total bindable data is the accumulation of all objects
 * received, meaning not all data has to be streammed at the same rate.  Any data in
 * an object received replaces the corresponding data in the accumulated data, or if
 * new, adds to the accumulated object.  You can think of the accumulated data as a
 * database with nested structures (or namespaces).
 *
 * @usage
 * @label Streaming Model
 * @group Transports, Models, and Codecs
 * @archetype <gc-model-streaming id="streaming"></gc-model-streaming>
 */
@Component({
    tag: 'gc-model-streaming',
    shadow: true
})

export class GcModelStreaming implements GcCodecBaseProps {
    private impl: StreamingDataModel | undefined = undefined;

    /**
     * The name of a specific channel for streaming data to and from.  This is optional and the
     * default is to stream all data.  When specified, the raw data must contain a member with the
     * same name as the channelName to hold channel specific data.
     *
     * @order 70
     */
    @Prop() channelName: string = undefined;

    /**
     * The amount of time to wait for data from the target when connecting.  The default is to
     * wait 10 mins. This gives the user time to perform any necessary manual actions, like
     * pressing a button on the board.  If you know the target will start sending information
     * automatically you can set this to a lower number.  And, if you want to prevent waiting for
     * data entirely, set the timeout to zero, but this is not recommended.
     *
     * @order 65
     */
    @Prop() timeout = 600000;

    // #region gc-target-configuration/gc-codec-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * A flag indicating that this model, transport, codec, or device is not necessary for connecting
     * to the target.  Any failure should not prevent the connection from continuing, which may
     * result in a partial connection.
     *
     * @order 77
     */
    @Prop() optional: boolean = false;

    /**
     * An optional identifier of a target device that is associated with this model, transport or codec.
     * Specifying a target device indicates that this component is necessary and/or optional for
     * properly connecting to the target device.  If a required component fails to connect, other components
     * will not be connected that are associated with the same device by id.  This way you can associate
     * a gc-target-program-loader with a gc-transport-usb so that if the program fails to load the transport
     * will not attempt to connect and will fail, unless the gc-target-program-loader has the optional property
     * set.  The absence of a target device indicates this is necessary and/or optional
     * for connecting to any device.  As a result, specifying the deviceId is not necessary if you only have
     * one device in you target configuration, any failure to connect will result in the entire connection
     * being aborted.
     *
     * @order 80
     */
    @Prop() deviceId: string;

    @Element() el: HTMLElement;
    // #endregion

    connectedCallback() {
        this.impl = new StreamingDataModel(this.el);
    }

    disconnectedCallback() {
        this.impl.dispose();
    }
}