/**
 *  Copyright (c) 2020, 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import { Component, Prop, Element, Watch, Method } from '@stencil/core';
import { GcCodecBaseProps } from '../gc-target-configuration/gc-codec-base-props';
import { RegisterModel, IRegisterModelParams } from './lib/RegisterModel';
import { createTargetParamsProxy } from '../gc-target-device-programmable/TargetDeviceParamsProxy';
import { GcTargetDeviceRegisterProps } from '../gc-target-device-analog/gc-target-device-register-props';
import { GcTargetDeviceAddressProps } from '../gc-target-device-analog/gc-target-device-address-props';
import { IRegisterJsonData } from './lib/IRegisterInfo';
import { GcModelPollingBaseProps } from '../gc-target-configuration/gc-model-polling-base-props';

/**
 * `gc-model-register` is a non visual component for a data binding model where
 * data is read and written from the target through registers.
 *
 * @usage
 * @label Register Model
 * @group Transports, Models, and Codecs
 * @archetype <gc-model-register id="reg"></gc-model-register>
 */
@Component({
    tag: 'gc-model-register',
    shadow: true
})

export class GcModelRegister implements GcCodecBaseProps, GcModelPollingBaseProps, GcTargetDeviceRegisterProps, GcTargetDeviceAddressProps, IRegisterModelParams {
    private impl: RegisterModel | undefined = undefined;

    /**
     * Method to set or change the register.json information programmatically, as opposed to providing a filename with the
     * **{@link registerInfo}** property.
     */
    @Method()
    async setSymbols(deviceInfo?: IRegisterJsonData) {
        this.impl.setSymbols(deviceInfo);
    }

    /**
     * Under normal operation, this register model will queue up register writes when the target is not connected,
     * to be performed when the device first becomes connected.  If this flag is set, then write operations are instead
     * discard when the target is disconnected, and will not write the values to the target upon connection.
     *
     * @order 98
     */
    @Prop() ignoreWriteOperationsWhenDisconnected: boolean = false;

    // #region gc-target-configuration/gc-codec-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * A flag indicating that this model, transport, codec, or device is not necessary for connecting
     * to the target.  Any failure should not prevent the connection from continuing, which may
     * result in a partial connection.
     *
     * @order 77
     */
    @Prop() optional: boolean = false;

    /**
     * An optional identifier of a target device that is associated with this model, transport or codec.
     * Specifying a target device indicates that this component is necessary and/or optional for
     * properly connecting to the target device.  If a required component fails to connect, other components
     * will not be connected that are associated with the same device by id.  This way you can associate
     * a gc-target-program-loader with a gc-transport-usb so that if the program fails to load the transport
     * will not attempt to connect and will fail, unless the gc-target-program-loader has the optional property
     * set.  The absence of a target device indicates this is necessary and/or optional
     * for connecting to any device.  As a result, specifying the deviceId is not necessary if you only have
     * one device in you target configuration, any failure to connect will result in the entire connection
     * being aborted.
     *
     * @order 80
     */
    @Prop() deviceId: string;

    @Element() el: HTMLElement;
    // #endregion
    // #region gc-target-configuration/gc-model-polling-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * Default refresh interval in milliseconds. Used when polling for data changes on the target.
     *
     * @order 61
     */
    @Prop() defaultRefreshInterval = 100;
    // #endregion
    // #region gc-target-device-analog/gc-target-device-register-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The relative or absolute path to a json file containing the register definitions for an analog device.name of the target device.
     *
     * @order 34
     */
    @Prop() registerInfo: string;

    /**
     * The name of the register to use for device verification.  If none specified, then no verification will occur.
     *
     * @order 58
     */
    @Prop() verifyRegisterName: string;

    /**
     * The value expected to be read from the verify register after applying the verification mask.  If not specified,
     * any value read for this register will be excepted as valid.
     *
     * @order 59
     */
    @Prop() verifyValue: string;

    /**
     * An optional mask value to be applied to the register value before comparing it to the verify value.  If not specified,
     * no mask will be applied, and the register value must match exactly the verify value.
     *
     * @order 60
     */
    @Prop() verifyMask: string;

    /**
     * An optional comma separated list of I2C device addresses to scan for verification of the device.
     * For example, verifyDeviceAddress="0x40,0x48,0x50".
     *
     * @order 62
     */
    @Prop() verifyDeviceAddress: string;

    /**
     * The optional flag that if true indicates that multi-device support is required.  All devices must be
     * of the same class, and therefore same register set.  Also, they all must be available on the same
     * interface through a single codec which also has multi-device support.
     *
     * @order 94
     */
    @Prop() isDeviceArray: boolean = false;
    // #endregion
    // #region gc-target-device-analog/gc-target-device-address-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The I2C bus address of this device.
     *
     * @order 39
     */
    @Prop() deviceAddress: string;
    // #endregion

    connectedCallback() {
        this.impl = new RegisterModel(createTargetParamsProxy(this.el));
    }

    disconnectedCallback() {
        this.impl.dispose();
    }

    @Watch('deviceId')
    onDeviceIdChanged(newValue: boolean, oldValue: boolean) {
        this.impl.onDeviceChanged();
    }
}
