/**
 *  Copyright (c) 2021, Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import { Prop, Component, Element } from '@stencil/core';
import { AevmCodec } from '../gc-codec-aevm/lib/AevmCodec';
import { GcCodecBaseProps } from '../gc-target-configuration/gc-codec-base-props';
import { GcCodecAnalogControllerBaseProps } from '../gc-target-configuration/gc-codec-analog-controller-base-props';
import { createTargetParamsProxy } from '../gc-target-device-programmable/TargetDeviceParamsProxy';

/**
 * `gc-codec-aevm` is a non visual component for encoding and decoding Analog EVM messages.
 *
 * @usage
 * @label AEVM Codec
 * @group Transports, Models, and Codecs
 * @archetype <gc-codec-aevm reset-controller-on-connect></gc-codec-aevm>
 */
@Component({
    tag: 'gc-codec-aevm',
    shadow: true
})

export class GcCodecAevm implements GcCodecAnalogControllerBaseProps, GcCodecBaseProps {
    private impl: AevmCodec | undefined;

    connectedCallback() {
        this.impl = new AevmCodec(createTargetParamsProxy(this.el));
    }

    disconnectedCallback() {
        this.impl.dispose();
    }

    /**
     * Send reset controller command during the onConnect phase.
     * If this flag is true, it will send the reset controller command before other commands.
     * If this flag is false, it will not send the reset controller command.
     *
     * @order 50
     */
    @Prop() resetControllerOnConnect = false;

    // #region gc-target-configuration/gc-codec-analog-controller-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * Connection timeout in milliseconds.
     *
     * @order 60
     */
    @Prop() connectTimeout = 250;

    /**
     * Maximum outstanding commands that can be sent to the target. Any additional commands
     * are queued up and will be resumed transmitting to the target when there is room.
     *
     * @order 61
     */
    @Prop() maxOutstandingCommands: number;

    // #endregion
    // #region gc-target-configuration/gc-codec-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * A flag indicating that this model, transport, codec, or device is not necessary for connecting
     * to the target.  Any failure should not prevent the connection from continuing, which may
     * result in a partial connection.
     *
     * @order 77
     */
    @Prop() optional: boolean = false;

    /**
     * An optional identifier of a target device that is associated with this model, transport or codec.
     * Specifying a target device indicates that this component is necessary and/or optional for
     * properly connecting to the target device.  If a required component fails to connect, other components
     * will not be connected that are associated with the same device by id.  This way you can associate
     * a gc-target-program-loader with a gc-transport-usb so that if the program fails to load the transport
     * will not attempt to connect and will fail, unless the gc-target-program-loader has the optional property
     * set.  The absence of a target device indicates this is necessary and/or optional
     * for connecting to any device.  As a result, specifying the deviceId is not necessary if you only have
     * one device in you target configuration, any failure to connect will result in the entire connection
     * being aborted.
     *
     * @order 80
     */
    @Prop() deviceId: string;

    @Element() el: HTMLElement;
    // #endregion

}
