/**
 *  Copyright (c) 2020, 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import { GcCodecBaseProps } from '../gc-target-configuration/gc-codec-base-props';
import { ProgramModel, IProgramModelParams } from '../gc-model-program/lib/ProgramModel';
import { Component, Prop, Element } from '@stencil/core';
import { GcTargetDeviceProgramLoaderProps } from '../gc-target-device-programmable/gc-target-device-program-loader-props';
import { GcTargetDeviceNameProps } from '../gc-target-device-programmable/gc-target-device-name-props';
import { createTargetParamsProxy } from '../gc-target-device-programmable/TargetDeviceParamsProxy';
import { GcModelPollingBaseProps } from '../gc-target-configuration/gc-model-polling-base-props';

/**
 * `gc-model-program` is a non visual component for a data binding model where
 * data is read and written from the target through global c variables using
 * the debug server and GEL expression evaluation.
 *
 * @usage
 * @label Program Model
 * @group Transports, Models, and Codecs
 * @archetype <gc-model-program id="pm"></gc-model-program>
 */
@Component({
    tag: 'gc-model-program',
    shadow: true
})

export class GcModelProgram implements GcCodecBaseProps, GcModelPollingBaseProps, GcTargetDeviceProgramLoaderProps, IProgramModelParams {
    private impl: ProgramModel | undefined = undefined;

    // #region gc-target-configuration/gc-codec-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * A flag indicating that this model, transport, codec, or device is not necessary for connecting
     * to the target.  Any failure should not prevent the connection from continuing, which may
     * result in a partial connection.
     *
     * @order 77
     */
    @Prop() optional: boolean = false;

    /**
     * An optional identifier of a target device that is associated with this model, transport or codec.
     * Specifying a target device indicates that this component is necessary and/or optional for
     * properly connecting to the target device.  If a required component fails to connect, other components
     * will not be connected that are associated with the same device by id.  This way you can associate
     * a gc-target-program-loader with a gc-transport-usb so that if the program fails to load the transport
     * will not attempt to connect and will fail, unless the gc-target-program-loader has the optional property
     * set.  The absence of a target device indicates this is necessary and/or optional
     * for connecting to any device.  As a result, specifying the deviceId is not necessary if you only have
     * one device in you target configuration, any failure to connect will result in the entire connection
     * being aborted.
     *
     * @order 80
     */
    @Prop() deviceId: string;

    @Element() el: HTMLElement;
    // #endregion
    // #region gc-target-configuration/gc-model-polling-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * Default refresh interval in milliseconds. Used when polling for data changes on the target.
     *
     * @order 61
     */
    @Prop() defaultRefreshInterval = 100;
    // #endregion
    // #region gc-target-device-programmable/gc-target-device-program-loader-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The name of the core to use.  This is optional and if omitted, the first
     * programmable core in the target configuration will be used.
     *
     * @order 47
     */
    @Prop() coreName: string;

    /**
     * The file path to the target program or binary image to use for the purposes of reading
     * symbols, and loading or flashing the program to the target.
     *
     * @order 48
     */
    @Prop() programOrBinPath: string;

    /**
     * The file path to the target program for the purposes of verifying if the device has the same
     * program before loading a binary file.  This is optional and is only useful when programOrBinPath
     * points to a binary image.
     *
     * @order 49
     */
    @Prop() verifyProgramPath: string;

    /**
     * The address to load a binary image into.  This is optional and is only useful when programOrBinPath
     * points to a binary image.  The address can be provided in hexadecimal notation if preceded by '0x'.
     *
     * @order 50
     */
    @Prop() loadAddress: number;

    /**
     * Timeout in millisecond for flashing/loading image onto the device.  This is optional and if omitted
     * the default is 75 seconds.  If more time is required, then this property should be set to an appropriate
     * higher value.
     *
     * @order 51
     */
    @Prop() timeout: number;

    /**
     * A flag indicating that the target program is stored in volatile static ram instead of flash memory.
     * Use this flag to indicate that the program image will not necessarily be preserved when reconnecting to
     * the same target, so the program must be loaded each time.
     *
     * @order 63
     */
    @Prop() sram: boolean = false;
    // #endregion

    /**
     * A flag indicating that only symbols should be loaded from the program image.  Setting this property
     * true will skip loading the prgram into memory and will assume that it is already loaded so only
     * symbols are needed to communicate with this device.
     *
     * @order 50
     */
    @Prop() symbolsOnly: boolean = false;

    connectedCallback() {
        this.impl = new ProgramModel(createTargetParamsProxy(this.el));
    }

    disconnectedCallback() {
        this.impl.dispose();
    }
}