/**
 *  Copyright (c) 2019, 2021 Texas Instruments Incorporated
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  *   Redistributions of source code must retain the above copyright
 *  notice, this list of conditions and the following disclaimer.
 *  notice, this list of conditions and the following disclaimer in the
 *  documentation and/or other materials provided with the distribution.
 *  *   Neither the name of Texas Instruments Incorporated nor the names of
 *  its contributors may be used to endorse or promote products derived
 *  from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 *  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 *  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 *  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 *  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 *  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 *  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 *  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 *  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
import { h, Component, Prop, Event, EventEmitter, Element, Method } from '@stencil/core';
import { WidgetBase } from '../gc-widget-base/gc-widget-base';
import { WidgetBaseProps } from '../gc-widget-base/gc-widget-base-props';
import { WidgetBaseTooltipProps } from '../gc-widget-base/gc-widget-base-tooltip-props';

/**
 * `gc-widget-label` is a bindable version of the <label> html element.
 *  By default, the labels hover color and underline color do not show unless explicitly set.
 *
 * @css --gc-color | color | #555555 { "kind": "color" }
 * @css --gc-color-hover | hover color | #555555 { "kind": "color" }
 * @css --gc-cursor-hover | hover cursor | default { "kind": "select", "options": ["", "help", "pointer", "progress"] }
 * @css --gc-font-size | font size | 14px
 * @css --gc-font-style | font style | inherit { "kind": "select", "options": ["", "normal", "italic", "oblique"] }
 * @css --gc-font-weight | font weight | normal { "kind": "select", "options": ["", "200", "300", "400", "500"] }
 * @css --gc-text-align | text align | { "kind": "select", "options": ["", "center", "left", "right"] }
 * @css --gc-text-decoration | text decoration | inherit { "kind": "select", "options": ["", "line-through", "overline", "underline"] }
 * @css --gc-text-decoration-hover | hover text decoration | inherit { "kind": "select", "options": ["", "line-through", "overline", "underline"] }
 * @label Label
 * @group Common
 * @demo
 * @usage
 */
@Component({
    tag: 'gc-widget-label',
    styleUrl: 'gc-widget-label.scss',
    shadow: true
})
export class WidgetLabel implements WidgetBaseProps, WidgetBaseTooltipProps {
    private base = new ( // keep on separate line to enable source mapping
        class extends WidgetBase {
            get element() {
                return (this.parent as WidgetLabel).el;
            }
        })(this);

    /**
     * The label to display for this widget
     * @type {string}
     * @order 2
     */
    @Prop() label: string = 'Label';

    render() {
        // JSXON
        return this.base.render(
            <label>{this.label}</label>,
            { tooltip: this.tooltip }
        );
        // JSXOFF
    }

    // #region gc-widget-base/gc-widget-base-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * The widget element.
     */
    @Element() el: HTMLElement;

    /**
     * Sets to `true` to hide the element, otherwise `false`.
     *
     * @order 200
     */
    @Prop({ reflect: true }) hidden: boolean = false;

    /**
     * Fired when a CSS property has changed.
     **/
    @Event({ eventName: 'css-property-changed' }) cssPropertyChanged: EventEmitter<{ name: string; value: string }>;

    /**
     * Sets the CSS property.
     *
     * @param {string} name the element style name
     * @param {string} value the new CSS property to be set
     */
    @Method()
    async setCSSProperty(name: string, value: string): Promise<void> {
        value = value.replace(/^[ ]+|[ ]+$/g, '');
        if (await this.getCSSProperty(name) !== value) {
            this.el.style.setProperty(name, value);
            this.cssPropertyChanged.emit({ name: name, value: value });
        }
    }

    /**
     * Returns the value of a CSS property.
     *
     * @param {string} name the element style property
     * @returns {string} the value of the property
     */
    @Method()
    async getCSSProperty(name: string): Promise<string> {
        return getComputedStyle(this.el).getPropertyValue(name).trim();
    }

    /**
     * Refresh the widget.
     */
    @Method()
    async refresh(): Promise<void> {
        return this.el['forceUpdate']();
    }
    // #endregion
    // #region gc-widget-base/gc-widget-base-tooltip-props.tsx:
    // -----------Autogenerated - do not edit--------------
    /**
     * Controls the tooltip that is displayed for this widget.
     * @order 210
     */
    @Prop() tooltip: string;
    // #endregion

}
